version: '3.8'

services:
  mongodb:
    build: ./mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: audiodb
  
  # audioserver:
  #   build: ./
  #   environment: 
  #     MONGO_URI: "mongodb://root:password@mongodb:27017"
  #   depends_on:
  #     - mongodb